### ISSUE TITLE
Loss Func 1

### ISSUE THREAD

**Issue by daren996** [chl8856/DeepHit#3]
Just wondering why the 'tmp1' (Line [120](https://github.com/chl8856/DeepHit/blob/master/class_DeepHit.py#L120) of Class_DeepHit.py) was assigned the same value as 'tmp2' (Line [124](https://github.com/chl8856/DeepHit/blob/master/class_DeepHit.py#L124) of Class_DeepHit).

**Comment by ShawnX4869** [comment]
Hi, did u clear the reason of this?
